# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: false

r_github_packages:
  - r-lib/covr
  - ecohealthalliance/fasterize

after_success:
  - Rscript -e 'covr::codecov(branch = "develop")'

notifications:
  email:
  on_success: change
on_failure: change
